# scripts/score_review_candidates.py
"""
This script takes the output from 'bootstrap_evaluation_set.py'
(i.e., 'candidates_for_review.json') and adds an 'auto_heuristic_score'
to each suggested candidate document.

This score is based on:
1. Lexical similarity between the query and the document title.
2. Lexical similarity between the query and the document snippet.
3. The original retrieval_score from the HybridRecommender.

The purpose is to help prioritize candidates for manual review when creating
the final 'evaluation_dataset.json'.
"""
import sys
import os
import json
import logging
import re
from typing import List, Dict, Any, Set

# --- Path Setup ---
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
# --- End Path Setup ---

from hybrid_search_rag import config # For potential path configurations if needed

logger = logging.getLogger(__name__)
if not logger.hasHandlers():
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(name)s - %(message)s')

def _preprocess_text_for_similarity(text: str) -> Set[str]:
    """
    Simple text preprocessing: lowercase, remove punctuation, split into words.
    Returns a set of unique words.
    """
    if not text or not isinstance(text, str):
        return set()
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text) # Remove punctuation
    return set(text.split())

def jaccard_similarity(set1: Set[str], set2: Set[str]) -> float:
    """
    Calculates Jaccard similarity between two sets of words.
    """
    if not set1 and not set2:
        return 1.0 # Or 0.0, depending on convention for two empty sets. 1.0 if they are "identical".
    if not set1 or not set2:
        return 0.0 # One is empty, the other is not.

    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
    return intersection / union if union > 0 else 0.0

def score_candidates(
    input_review_file_path: str,
    output_scored_file_path: str,
    title_weight: float = 0.3,
    snippet_weight: float = 0.4,
    original_score_weight: float = 0.3,
    sort_candidates: bool = True
):
    """
    Scores candidates in the review file and saves the enhanced data.

    Args:
        input_review_file_path: Path to the JSON file generated by bootstrap_evaluation_set.py.
        output_scored_file_path: Path to save the new JSON file with scored candidates.
        title_weight: Weight for title similarity in the heuristic score.
        snippet_weight: Weight for snippet similarity in the heuristic score.
        original_score_weight: Weight for the original retrieval_score.
        sort_candidates: If True, sorts candidates within each query by the new heuristic score.
    """
    logger.info(f"Loading candidates for review from: {input_review_file_path}")
    try:
        with open(input_review_file_path, 'r', encoding='utf-8') as f:
            review_data = json.load(f)
    except FileNotFoundError:
        logger.error(f"Input file not found: {input_review_file_path}")
        return
    except json.JSONDecodeError as e:
        logger.error(f"Error decoding JSON from {input_review_file_path}: {e}")
        return

    scored_review_data = []
    total_queries = len(review_data)
    logger.info(f"Scoring candidates for {total_queries} queries...")

    for i, query_item in enumerate(review_data):
        query_text = query_item.get("query_text", "")
        query_words = _preprocess_text_for_similarity(query_text)
        
        logger.debug(f"Processing query {i+1}/{total_queries}: {query_item.get('query_id')}")

        scored_candidates = []
        original_candidates = query_item.get("suggested_candidates_for_review", [])

        # Normalize original retrieval_scores for this query's candidates (0 to 1)
        # to make them comparable if their scales vary wildly.
        # This is optional; direct use might be fine if scores are somewhat consistent.
        retrieval_scores = [cand.get("retrieval_score", 0.0) for cand in original_candidates]
        min_score = min(retrieval_scores) if retrieval_scores else 0.0
        max_score = max(retrieval_scores) if retrieval_scores else 0.0
        score_range = max_score - min_score

        for candidate in original_candidates:
            doc_title = candidate.get("doc_title", "")
            doc_snippet = candidate.get("doc_snippet", "") # Assuming key from bootstrap script
            original_ret_score = candidate.get("retrieval_score", 0.0)

            title_words = _preprocess_text_for_similarity(doc_title)
            snippet_words = _preprocess_text_for_similarity(doc_snippet)

            title_sim = jaccard_similarity(query_words, title_words)
            snippet_sim = jaccard_similarity(query_words, snippet_words)

            # Normalize original score (0-1 range for this query's candidates)
            # If all scores are the same, normalized score will be 0 unless range is 0.
            # If score_range is 0, all scores are same; assign a mid-value (e.g. 0.5) or 0 or 1.
            normalized_original_score = 0.0
            if score_range > 0:
                normalized_original_score = (original_ret_score - min_score) / score_range
            elif retrieval_scores: # All scores are the same
                 normalized_original_score = 0.5 # Or 1.0 if high scores, 0.0 if low.

            # Calculate combined heuristic score
            auto_heuristic_score = (
                (title_weight * title_sim) +
                (snippet_weight * snippet_sim) +
                (original_score_weight * normalized_original_score) # Using normalized score
            )

            # Add new scores to the candidate dictionary
            updated_candidate = candidate.copy() # Avoid modifying original dict in list
            updated_candidate["similarity_title"] = title_sim
            updated_candidate["similarity_snippet"] = snippet_sim
            updated_candidate["normalized_retrieval_score"] = normalized_original_score
            updated_candidate["auto_heuristic_score"] = auto_heuristic_score
            scored_candidates.append(updated_candidate)

        if sort_candidates:
            scored_candidates.sort(key=lambda x: x["auto_heuristic_score"], reverse=True)

        new_query_item = query_item.copy()
        new_query_item["suggested_candidates_for_review"] = scored_candidates
        scored_review_data.append(new_query_item)

    # Save the scored data
    try:
        output_dir = os.path.dirname(output_scored_file_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        with open(output_scored_file_path, 'w', encoding='utf-8') as f_out:
            json.dump(scored_review_data, f_out, indent=2)
        logger.info(f"Successfully saved scored candidates to: {output_scored_file_path}")
        logger.info("You can now use this file to help prioritize your manual review.")
    except Exception as e:
        logger.error(f"Error saving the scored review file: {e}", exc_info=True)


if __name__ == '__main__':
    # Define input and output file paths
    # Assumes 'candidates_for_review.json' is in 'data_store/evaluation_sets/'
    # and the output will also be saved there.
    input_file = os.path.join(project_root, "data_store", "evaluation_sets", "candidates_for_review.json")
    output_file = os.path.join(project_root, "data_store", "evaluation_sets", "scored_candidates_for_review.json")

    # Weights for combining scores (can be tuned)
    # Ensure they sum to 1 if you want a normalized weighted average feel, though not strictly necessary.
    TITLE_SIM_WEIGHT = 0.3
    SNIPPET_SIM_WEIGHT = 0.5 # Give more weight to snippet content
    ORIGINAL_SCORE_WEIGHT = 0.2

    if not os.path.exists(input_file):
        logger.error(f"Input file '{input_file}' not found. Please run 'bootstrap_evaluation_set.py' first.")
    else:
        score_candidates(
            input_review_file_path=input_file,
            output_scored_file_path=output_file,
            title_weight=TITLE_SIM_WEIGHT,
            snippet_weight=SNIPPET_SIM_WEIGHT,
            original_score_weight=ORIGINAL_SCORE_WEIGHT,
            sort_candidates=True
        )
